# -*- coding: utf-8 -*-
"""13_raman.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cIAoyGUPiaS62Af3MWoC9x8DrDBZ781F
"""

import streamlit as st
import joblib
import pandas as pd

# Load model and encoders
model = joblib.load("13_Jyoti_Raman_model.pkl")
encoders = joblib.load("label_encoder_13_Jyoti_Raman.pkl")

st.set_page_config(page_title="🌾 Crop Yield Predictor", layout="centered")

st.title("🌾 Crop Yield Prediction App")
st.markdown("Predict crop yield based on farming conditions")

# ---------- INPUTS ----------

region = st.selectbox("Region", encoders["Region"].classes_)
soil = st.selectbox("Soil Type", encoders["Soil_Type"].classes_)
crop = st.selectbox("Crop", encoders["Crop"].classes_)
weather = st.selectbox("Weather Condition", encoders["Weather_Condition"].classes_)

rainfall = st.slider("Rainfall (mm)", 0, 500, 100)
temperature = st.slider("Temperature (°C)", 0, 50, 25)
fertilizer = st.selectbox("Fertilizer Used", [0, 1])
irrigation = st.selectbox("Irrigation Used", [0, 1])
days = st.slider("Days to Harvest", 30, 365, 120)

# ---------- ENCODING ----------
input_data = pd.DataFrame({
    "Region": [encoders["Region"].transform([region])[0]],
    "Soil_Type": [encoders["Soil_Type"].transform([soil])[0]],
    "Crop": [encoders["Crop"].transform([crop])[0]],
    "Rainfall_mm": [rainfall],
    "Temperature_Celsius": [temperature],
    "Fertilizer_Used": [fertilizer],
    "Irrigation_Used": [irrigation],
    "Weather_Condition": [encoders["Weather_Condition"].transform([weather])[0]],
    "Days_to_Harvest": [days]
})

# ---------- PREDICTION ----------
if st.button("Predict Yield"):
    prediction = model.predict(input_data)[0]

    st.success(f"🌾 Estimated Yield: {prediction:.2f} tons/hectare")